[workspace.package]
version = "1.0.0"
edition = "2021"
publish = false

[workspace]
members = [
    "builder",
    "app",
]

resolver = "2"

[workspace.dependencies]
prost = { version = "0.12" }
prost-types = { version = "0.12" }
prost-build = { version = "0.12" }
